services:

  backend-service:


    image: shlomtzion2608/image-generator-backend-image:1.0

    build: ./Backend

    container_name: "image-generator-backend-container" 
    
    ports:
      - 4000:4000

    restart: unless-stopped

    environment:
      DALLE3URL : "https://api.openai.com/v1/images/generations"
      PORT: 4000 

  
  frontend-service:
    
 
    image: shlomtzion2608/image-generator-frontend-image:1.0

    build: ./Frontend

    container_name: image-generator-frontend-container

    ports:
      - 80:3000

    restart: unless-stopped


      
    
